# numpy library

In [1]:
import numpy as numpy

## 1. Data Type & attributes

In [12]:
#creating an array
a1 = numpy.array([[1, 2, 3], [4, 5, 6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# shape mentions the shape of the array
a1.shape 

(2, 3)

In [14]:
a2 = numpy.array([[1, 2, 3], [10, 20, 30]])
a2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [14]:
a2.shape

(2, 3)

In [15]:
    # Same array as slide in video
    a3 = numpy.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]],
                   [[13, 14, 15],
                    [16, 17, 18]]])

In [4]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [12]:
a3.shape

(3, 2, 3)

In [17]:
# ndim = mentions the dimensions of the array
a1.ndim

2

In [18]:
a2.ndim

2

In [19]:
a3.shape, a2.shape

((3, 2, 3), (2, 3))

In [21]:
# size = how many elements we've in the Array
a1.size

6

In [23]:
# dtypes = what type of data does the array have
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [24]:
# type() = what type of data is it
type(a1)

numpy.ndarray

### pandas is built on top of numpy

creating a (pandas)dataframe from a (numpy)ndarray

In [4]:
import pandas as pandas

In [26]:
df = pandas.DataFrame(a2)
df

0   1   2
0   1   2   3
1  10  20  30

## 2. Creating Arrays

In [66]:
# ones() = this will create a ndarray of your preferred shape and dtype
ones = numpy.ones((3, 2))

In [32]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
# zeros() = will create a ndarray of your preferred shape and dtype
zeros = numpy.zeros((3, 2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
# arange() [with a single R] = will create a ndarray of start, stop, interval values
range_array = numpy.arange(0, 20, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18])

In [188]:
# random.randint() = will throw back a ndarray which will have a specific starting, ending point and size. 
random = numpy.random.randint(0, 10, size = (3, 5))
random

array([[7, 7, 8, 1, 5],
       [9, 8, 9, 4, 3],
       [0, 3, 5, 0, 2]])

Inferences: for values starting from 0 (inclusive) to 10 (exclusive) for 3 rows and 5 columns a ndarray will be shared back with random digits. 

In [39]:
random.shape

(3, 5)

In [40]:
# random.random() = will show a ndarray betweeo 0 to 1 for given size
random2 = numpy.random.random(size=(3, 3))
random2

array([[0.31675027, 0.50032408, 0.36935893],
       [0.27287728, 0.46336157, 0.32260649],
       [0.6802501 , 0.49933271, 0.32208764]])

In [41]:
random2.shape

(3, 3)

In [44]:
random3 = numpy.random.rand(3, 3)
random3

array([[0.21205202, 0.47838491, 0.17446651],
       [0.0342262 , 0.47168404, 0.45644088],
       [0.99044986, 0.50975427, 0.33084834]])

In [4]:
numpy.random.rand()

0.25216054111976527

In [6]:
random4 = numpy.random.randint(10, size = (5,3))
random4 # running this each time we get different results

array([[8, 7, 5],
       [4, 0, 0],
       [0, 0, 3],
       [2, 3, 4],
       [9, 4, 7]])

In [9]:
numpy.random.seed(5)
random4 = numpy.random.randint(10, size = (5,3))
random4 # running this each time gives the same results, 
        # it ensures that the values generated randomly are reproducible.

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0],
       [0, 7, 1],
       [5, 7, 0]])

## 3. Viewing Arrays & Matrices

In [10]:
numpy.unique(random4)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

#### In case of 2D Array, if you call by the index, it will fetch the particular row.

In [17]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a1[0]

array([1, 2, 3])

#### In case of 3D Array, calling by the index, it will fetch the first matrice/array.

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [21]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a3.shape

(3, 2, 3)

In [26]:
a4 = numpy.array([[[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]],
                  [[10, 11, 12], 
                   [13, 14, 15],
                   [16, 17, 18]]])

In [27]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [28]:
a4.shape

(2, 3, 3)

In [29]:
a4[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Even though the index mentioned is more than the value of the Axis, no error is thrown. 

In [33]:
a4.shape

(2, 3, 3)

In [34]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a4[:3, :2, :4]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

#### Other types of simple indexing

In [43]:
a5 = numpy.random.randint(10, size = (2, 3, 4, 5))
a5

array([[[[8, 0, 9, 1, 9],
         [0, 8, 7, 7, 9],
         [4, 1, 4, 2, 1],
         [7, 5, 4, 2, 2]],

        [[1, 2, 3, 1, 2],
         [4, 9, 0, 1, 2],
         [3, 8, 5, 5, 4],
         [3, 9, 5, 9, 6]],

        [[9, 5, 1, 1, 0],
         [8, 0, 5, 9, 3],
         [3, 0, 3, 7, 3],
         [7, 3, 2, 6, 6]]],


       [[[2, 7, 0, 3, 7],
         [5, 1, 6, 7, 3],
         [9, 7, 9, 7, 6],
         [6, 4, 5, 4, 0]],

        [[0, 1, 5, 3, 1],
         [7, 0, 9, 8, 3],
         [4, 4, 9, 9, 6],
         [7, 9, 6, 0, 7]],

        [[1, 3, 9, 3, 3],
         [3, 5, 1, 0, 0],
         [2, 2, 8, 9, 1],
         [8, 6, 7, 9, 6]]]])

In [63]:
# Get the first 4 numbers of the innermost array
a5[:, 1, 0, ]

array([[1, 2, 3, 1, 2],
       [0, 1, 5, 3, 1]])

In [44]:
a1 

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a1.shape

(2, 3)

In [46]:
a1[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a1[:1]

array([[1, 2, 3]])

In [49]:
a1[1:]

array([[4, 5, 6]])

In [50]:
a1[1:, :1] 

array([[4]])

In [51]:
a1[:1, 2:] 

array([[3]])

In [52]:
a1[:1, 1:]

array([[2, 3]])

In [55]:
a1[:,1:]

array([[2, 3],
       [5, 6]])

## 4. Manipulating Arrays & Comparing Arrays

### (4.1) Arithmetic

In [64]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
ones2 = numpy.ones(shape = (2, 3))
ones2

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Addition

In [73]:
a1 + ones2

array([[2., 3., 4.],
       [5., 6., 7.]])

In [88]:
numpy.add(a1, ones2)

array([[2., 3., 4.],
       [5., 6., 7.]])

#### Subtraction

In [74]:
a1 - ones2

array([[0., 1., 2.],
       [3., 4., 5.]])

In [89]:
numpy.subtract(a1, ones2)

array([[0., 1., 2.],
       [3., 4., 5.]])

#### Multiplication

In [75]:
a1 * ones2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [90]:
numpy.multiply(a1, ones2)

array([[1., 2., 3.],
       [4., 5., 6.]])

#### Division

In [76]:
a1 / ones2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [91]:
numpy.divide(a1, ones2)

array([[1., 2., 3.],
       [4., 5., 6.]])

#### Floor Division (removes decimal, rounds it off to nearest decimal)

In [84]:
a6 = numpy.array([[1, 2, 3.3],[4, 5, 6.5]])
a6

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [86]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
a6 // a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
numpy.floor_divide(a6, a1)

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Power of

In [87]:
a2 ** 2

array([[  1,   4,   9],
       [100, 400, 900]], dtype=int32)

In [92]:
numpy.power(a2, 2)

array([[  1,   4,   9],
       [100, 400, 900]], dtype=int32)

#### Modulo (remainder after division)

In [93]:
a2 % a1

array([[0, 0, 0],
       [2, 0, 0]], dtype=int32)

In [94]:
numpy.mod(a2, a1)

array([[0, 0, 0],
       [2, 0, 0]], dtype=int32)

#### Exponential

In [97]:
numpy.exp(a1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

#### Logs

In [99]:
numpy.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [2.30258509, 2.99573227, 3.40119738]])

### (4.2) Broadcasting

In [110]:
a3.shape, a4.shape

((3, 2, 3), (2, 3, 3))

In [111]:
(a3 + a4).shape

ValueError: operands could not be broadcast together with shapes (3,2,3) (2,3,3) 

### to fix the above issue, reshape a3

### you can also Transpose the 2nd array, you'll see the sample little down.. 

In [117]:
aa3 = a3.reshape(3, 2, 3, 1)

In [118]:
(aa3 + a4).shape

(3, 2, 3, 3)

In [119]:
aa3 + a4

array([[[[ 2,  3,  4],
         [ 6,  7,  8],
         [10, 11, 12]],

        [[14, 15, 16],
         [18, 19, 20],
         [22, 23, 24]]],


       [[[ 8,  9, 10],
         [12, 13, 14],
         [16, 17, 18]],

        [[20, 21, 22],
         [24, 25, 26],
         [28, 29, 30]]],


       [[[14, 15, 16],
         [18, 19, 20],
         [22, 23, 24]],

        [[26, 27, 28],
         [30, 31, 32],
         [34, 35, 36]]]])

## Voila!!

###  (4.3) Aggregation

Aggregation = performing a particular operation on no of elements

In [121]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
sum(a1) # doesn't behave well on the numpy array, different to what was shown in video lectures 

array([5, 7, 9])

In [165]:
numpy.sum(a1) 

21

In [123]:
listy = [1, 2, 3, 4] # works well on python list
sum(listy)

10

General Thumbrule : Use Python function `sum()` on python data types.. Use Numpy function `numpy.sum()` on numpy data types.. 

In [127]:
massive_array = numpy.random.random(100000)

In [129]:
massive_array[:10]

array([0.48361506, 0.14038611, 0.07544315, 0.68808941, 0.82006319,
       0.61670132, 0.89608079, 0.63052799, 0.80032326, 0.36206458])

In [130]:
%timeit sum(massive_array)
%timeit numpy.sum(massive_array)

9.96 ms ± 409 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
47.3 µs ± 518 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Variance

In [131]:
numpy.var(a1)

2.9166666666666665

Standard Deviation

In [132]:
numpy.std(a1)

1.707825127659933

Standard Deviation = SQRT (Variance)

In [133]:
numpy.sqrt(numpy.var(a1))

1.707825127659933

In [134]:
high_var = numpy.array([1, 300, 800, 4000, 8000])
low_var = numpy.array([2, 4, 6, 8, 10])

In [135]:
numpy.var(high_var), numpy.var(low_var)

(9280552.16, 8.0)

In [136]:
numpy.std(high_var), numpy.std(low_var)

(3046.399868697476, 2.8284271247461903)

#### Transpose

In [138]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
a1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Dot Product

In [142]:
numpy.random.seed(0)
mat1 = numpy.random.randint(0, 10, size = (5, 3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [144]:
mat2 = numpy.random.randint(0, 10, size = (5, 3))
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [145]:
numpy.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

####  To solve the above issue we need to Transpose the Array

In [146]:
numpy.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [161]:
numpy.random.seed(0)
mat3 = numpy.random.randint(0, 10, size = (2, 1, 4))
mat3

array([[[5, 0, 3, 3]],

       [[7, 9, 3, 5]]])

In [162]:
mat4 = numpy.random.randint(0, 10, size = (2, 1, 4))
mat4

array([[[2, 4, 7, 6]],

       [[8, 8, 1, 6]]])

In [163]:
numpy.dot(mat3, mat4)

ValueError: shapes (2,1,4) and (2,1,4) not aligned: 4 (dim 2) != 1 (dim 1)

### Incase of Matrices > 2D, dot() will compare last AXIS of 1st matrix and second-last AXIS of 2nd matrix

In [164]:
numpy.dot(mat3, mat4.reshape(2, 4, 1))

array([[[[ 49],
         [ 61]]],


       [[[101],
         [161]]]])

### Dot Product (Nut Butter Sales Example)

In [168]:
# No of jars sold
jars_sold = numpy.array([[2, 7, 1],
                       [9, 4, 16], 
                       [11, 14, 18],
                       [13, 13, 16], 
                       [15, 18, 9]])

In [169]:
# Cost of each Butter
cost = numpy.array([10, 8, 12])

In [170]:
# Dot Product of both
numpy.dot(jars_sold, cost)

array([ 88, 314, 438, 426, 402])

In [171]:
# Creating Weekly Sales Dataframe
weekly_sales = pandas.DataFrame(jars_sold, index = ["Mon", "Tue", "Wed", "Thur", "Fri"], 
                                columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               2              7              1
Tue               9              4             16
Wed              11             14             18
Thur             13             13             16
Fri              15             18              9

In [173]:
# Creating Prices DataFrame
prices = pandas.DataFrame(cost.reshape(1,3), index = ["Price"], 
                          columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [174]:
weekly_sales.shape, prices.shape

((5, 3), (1, 3))

In [175]:
total = weekly_sales.dot(prices.T)

In [176]:
total

Price
Mon      88
Tue     314
Wed     438
Thur    426
Fri     402

In [177]:
weekly_sales['Total'] = total

In [178]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon               2              7              1     88
Tue               9              4             16    314
Wed              11             14             18    438
Thur             13             13             16    426
Fri              15             18              9    402

### (4.4) Comparision Operators

In [179]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
a2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [181]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [182]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [183]:
a1 == a1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [184]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [185]:
a1 > 5

array([[False, False, False],
       [False, False,  True]])

## 5. Sorting Arrays

In [189]:
random

array([[7, 7, 8, 1, 5],
       [9, 8, 9, 4, 3],
       [0, 3, 5, 0, 2]])

In [190]:
numpy.sort(random)

array([[1, 5, 7, 7, 8],
       [3, 4, 8, 9, 9],
       [0, 0, 2, 3, 5]])

In [191]:
numpy.argsort(random)

array([[3, 4, 0, 1, 2],
       [4, 3, 1, 0, 2],
       [0, 3, 4, 1, 2]], dtype=int64)

In [192]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [194]:
numpy.argmax(a1) # `a1[5] = 6` is the value held. Hence, it's returning the index value of 5

5

In [200]:
random

array([[7, 7, 8, 1, 5],
       [9, 8, 9, 4, 3],
       [0, 3, 5, 0, 2]])

In [198]:
# AXIS = 0 (COLUMNS) returns index of the max value on each column
numpy.argmax(random, axis = 0) 

array([1, 1, 1, 1, 0], dtype=int64)

In [199]:
# AXIS = 1 (ROWS) returns index of the max value on each row
numpy.argmax(random, axis = 1)

array([2, 0, 2], dtype=int64)

### 6. Practical Example - NumPy in action!!!

<img src = "zero-to-mastery-ml-master/images/numpy-panda.png"/>

In [6]:
from matplotlib.image import imread

In [7]:
panda = imread('zero-to-mastery-ml-master/images/numpy-panda.png')

In [8]:
panda[:1]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

Similarly, another image

<img src = 'zero-to-mastery-ml-master/images/numpy-dog-photo.png'/>

In [10]:
numpy_dogs = imread('zero-to-mastery-ml-master/images/numpy-dog-photo.png')

In [11]:
numpy_dogs[:2]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]]], dtype=float32)